from django.urls import path
from .views import *
import urllib.parse

urlpatterns = [
    path("", index),
    path("registration/", registration, name = "registration"),
    path("registrationForAdmin/", registrationForAdmin, name = "registrationForAdmin"),
    path("validate_login/", validate_login, name="validate_login"),
    path("login/", login),
    path("editVisual0/", editVisual0),
    path("editVisual1/", editVisual1),
    path("editVisualAll0/<int:id>/", editVisualAll0),
    path("editVisualAll1/<int:id>/", editVisualAll1),
    path("personalArea/", editUser),
    path("tagUsers/", tagUsers),
    path("saveEdit/<int:id>/<str:tag>/", saveEdit),
    path("saveEditTask/<int:id>/<str:description>/<path:link>/<str:state>/<int:executorId>/", saveEditTask),
    path("mainSaveEditTask/<int:id>/<str:state>/<int:executorId>/", mainSaveEditTask),
    path("mainUserSaveEditTask/<int:id>/<str:description>/<path:link>/<str:state>/", mainUserSaveEditTask),
    path("tasksUserSaveEditTask/<int:id>/<str:state>/<int:executorId>", tasksUserSaveEditTask),
    path("mainUserSaveEditTask1/<int:id>/<str:state>/", mainUserSaveEditTask1),
    path("tasksSaveEditTask/<int:id>/<str:state>/", tasksSaveEditTask),
    path("delete/<int:id>/", delete),
    path("projects/deleteProject/<int:id>/", deleteProject),
    path("projects/tasks/deleteTask/<int:id>/", deleteTask),
    path("deleteTaskMain/<int:id>/", deleteTaskMain),
    path("logout/", logout),
    path("projects/", projectsForm),
    path("projects/newProjectForm/", newProjectForm, name = "newProjectForm"),
    path("projects/editProject/<int:id>/", editProject),
    path("projects/newTask/<int:id>/", newTaskForm, name = "newTaskForm"),
    path("projects/tasks/<int:id>/", taskForm),
    path("personalArea/deleteTag/<int:id>/", deleteTag),
    path("saveMessage/<int:id>/<int:idUser>/<str:message>/", saveMessage),
    path("inTaskEditDateEnd/<int:id>/<str:dateEnd>/", inTaskEditDateEnd),
    path("inTaskEditLink/<int:id>/<path:link>/", inTaskEditLink),
    path("inTaskEditComment/<int:id>/<str:description>/", inTaskEditDescription),
    path("inTaskEditExecutor/<int:id>/<str:executor>/", inTaskEditExecutor),
    path("inTaskEditState/<int:id>/<str:state>/", inTaskEditState),
    path("inTaskEditTitle/<int:id>/<str:title>/", inTaskEditTitle),

    path("task/<int:id>/", fallInTask),

    path("statistics/", statistics),
    path("saveEditProjectState/<int:id>/<str:state>/", saveEditProjectState),
]