# Generated by Django 5.0.1 on 2024-01-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagementApplication', '0005_user_color_user_visual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='visual',
            field=models.IntegerField(),
        ),
    ]
