# Generated by Django 5.0.1 on 2024-01-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagementApplication', '0006_alter_user_visual'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProject', models.IntegerField()),
                ('idTask', models.IntegerField()),
                ('idExecutor', models.IntegerField()),
                ('executor', models.CharField(max_length=100)),
                ('idResponsible', models.IntegerField()),
                ('responsible', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField()),
                ('idUser', models.IntegerField()),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='color',
            new_name='style',
        ),
    ]
