# Generated by Django 5.0.1 on 2024-02-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagementApplication', '0008_message_idcs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.TextField(),
        ),
    ]
