# Generated by Django 5.0.4 on 2024-04-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagementApplication', '0011_message_iduserrecipient_message_messagestatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='messageText',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='userName',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='comment',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='comment',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='executor',
            new_name='executorName',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='responsible',
            new_name='responsibleName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='comment',
            new_name='note',
        ),
        migrations.AddField(
            model_name='task',
            name='idResponsible',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
